<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Setting_main-panel_1</name>
   <tag></tag>
   <elementGuidId>784cd2e7-a37e-45e5-ab0e-62fc449f92bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l-main']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;ProfileFirst nameLast namedefault Heading 1 Heading 2 Heading 3 Heading 4 Headin&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d82d2a31-a65d-49a0-aa0f-295238023e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-panel</value>
      <webElementGuid>9d333778-7875-420f-b2b0-f73efe26009f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I'am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate</value>
      <webElementGuid>fee6f7e5-44cd-41b2-a250-712fb9ada9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-main&quot;)/div[@class=&quot;main-panel&quot;]</value>
      <webElementGuid>38ff9413-24e5-4a0e-97d7-d73d4ea73126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]</value>
      <webElementGuid>3f485f4c-79da-46c8-97d8-9a57511c5ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::div[2]</value>
      <webElementGuid>8c995e8b-5c16-48ec-b942-bff67b368da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import data'])[1]/following::div[4]</value>
      <webElementGuid>19774d18-1706-476b-bbd5-1a26b364aa9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-main-builder/div/div[4]</value>
      <webElementGuid>25d9ed04-bf95-40b9-aa63-f422cbb01a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;) or . = concat(&quot;ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;))]</value>
      <webElementGuid>3fbaa959-c53f-45b3-b47c-cbda25383b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
