<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Setting_w-100</name>
   <tag></tag>
   <elementGuidId>02724081-4571-4625-94bc-de4b0f734932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l-main']/div[4]/app-my-info-builder/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ProfileFirst nameLast namedefault Heading 1 Heading 2 Heading 3 Heading 4 Headin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>574899eb-4795-44b9-a6b7-e08bc45d4520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>b00cd631-2e51-42be-9e98-84ad1ac22f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I'am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate</value>
      <webElementGuid>2b7e3df1-15f2-4c47-9074-f82f955aec42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-main&quot;)/div[@class=&quot;main-panel&quot;]/app-my-info-builder[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]</value>
      <webElementGuid>1c5fc15c-8b8b-403d-b57b-42bcb21e7d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]/app-my-info-builder/div</value>
      <webElementGuid>8941744b-756a-4c48-b2e9-67853ed7c792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::div[3]</value>
      <webElementGuid>c2b96b0f-d091-4b41-a50d-9dfa8fe01941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import data'])[1]/following::div[5]</value>
      <webElementGuid>d4ac8a9a-ae6b-42c9-949a-627777a40837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-my-info-builder/div</value>
      <webElementGuid>85610c2d-4117-46ac-924f-029fe45ff87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;) or . = concat(&quot;ProfileFirst nameLast namedefault  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;))]</value>
      <webElementGuid>0ee49633-c81b-4c23-8b69-e4ab843e9c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
