<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Setting_main-panel</name>
   <tag></tag>
   <elementGuidId>8386a03c-8556-4665-b3b7-068e2db6f659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l-main']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;ProfileFirst nameLast nameHeading 1 Heading 1 Heading 2 Heading 3 Heading 4 Head&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc29fc23-9b3d-4eee-9dc4-7e12a52a2744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-panel</value>
      <webElementGuid>582a1eff-6756-433c-b91b-2aa9e691c2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProfileFirst nameLast nameHeading 1  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I'am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate</value>
      <webElementGuid>0c4b980c-d7cb-4fdd-a558-5346732c4d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-main&quot;)/div[@class=&quot;main-panel&quot;]</value>
      <webElementGuid>352b4e36-8452-4d18-a527-71eb8af4cf38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]</value>
      <webElementGuid>b6370722-09ed-4299-8b4f-c21dbec507a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::div[2]</value>
      <webElementGuid>bbcd9065-470a-448f-8586-919c9242f499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import data'])[1]/following::div[4]</value>
      <webElementGuid>8a7c4a90-e672-4168-9306-36d87e6a03a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-main-builder/div/div[4]</value>
      <webElementGuid>ddb0958c-b832-4c49-85ed-52494e7f853e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;ProfileFirst nameLast nameHeading 1  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;) or . = concat(&quot;ProfileFirst nameLast nameHeading 1  Heading 1  Heading 2  Heading 3  Heading 4  Heading 5  Heading 6  Heading 7  Paragraph  Predefined  Standard  default Arial  Arial  Times New Roman  Calibri  Comic Sans MS 3  1  2  3  4  5  6  7 Clear Class  Clear Class  quote  redText  titleText Hi,I&quot; , &quot;'&quot; , &quot;am DuyFull Stack DeveloperDescriptionSloganBirth dayPhone numberCity, ProvinceAddressChange avatarUpdate&quot;))]</value>
      <webElementGuid>a510c0e6-c08c-4766-ade9-36e91e0dd6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
