<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font</name>
   <tag></tag>
   <elementGuidId>bc1c40c6-55af-46b4-a724-7a86b05214f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l-main']/div[4]/app-my-info-builder/div/div[3]/div/span/angular-editor/div/div/div/h1/font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;TEst&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>2e452a28-d506-4207-8d39-b9e25bb271da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#d72d2d</value>
      <webElementGuid>cad42d89-7cc0-42e0-9361-832d8f3d898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEst</value>
      <webElementGuid>a4a80e57-40cf-443b-958e-65baee9f1051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-main&quot;)/div[@class=&quot;main-panel&quot;]/app-my-info-builder[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;flex flex-row mb-8&quot;]/div[@class=&quot;p-fluid w-full&quot;]/span[@class=&quot;p-float-label&quot;]/angular-editor[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;angular-editor&quot;]/div[@class=&quot;angular-editor-wrapper&quot;]/div[@class=&quot;angular-editor-textarea&quot;]/h1[@class=&quot;home__title&quot;]/font[1]</value>
      <webElementGuid>b1151133-67d2-46bb-b328-6db01bd287e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]/app-my-info-builder/div/div[3]/div/span/angular-editor/div/div/div/h1/font</value>
      <webElementGuid>10d9ab06-1da8-4302-8f44-447df2b3ece4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='titleText'])[1]/following::font[1]</value>
      <webElementGuid>1def78cc-8078-4743-8dee-5fed37f8f511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::font[1]</value>
      <webElementGuid>70d5bf09-964b-4e94-9c80-90a8431778e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slogan'])[1]/preceding::font[1]</value>
      <webElementGuid>5ba4628f-c5f2-4bfc-88b5-c8fc1707ca91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEst']/parent::*</value>
      <webElementGuid>74294902-157b-439c-9869-89a330f07068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//font</value>
      <webElementGuid>ba15e81b-c8c3-4854-837b-94eb0932e35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = 'TEst' or . = 'TEst')]</value>
      <webElementGuid>d8c6026b-5799-4e48-b859-e1822f125f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
