<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slogan_calendar</name>
   <tag></tag>
   <elementGuidId>9a29bb5a-312e-43dd-9833-56994d63f286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Birth day&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eded023-7355-4b85-a503-a7e759448004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c19accb-ccb3-47fa-9bfe-4c0198138126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c784a814-febe-4075-842a-c4201cdc41d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c66-31 p-inputtext p-component ng-star-inserted</value>
      <webElementGuid>b35dc922-a7fd-46fa-a7a3-7eb29d005c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>2494c1cd-07b1-46f6-bd3b-51c09cf794de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar&quot;)</value>
      <webElementGuid>64dd9814-5c4f-44c8-ac60-758de97d27b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar']</value>
      <webElementGuid>c23d7a0c-4814-47ff-97b0-877f9ca32166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]/app-my-info-builder/div/div[4]/div/span/p-calendar/span/input</value>
      <webElementGuid>f3d5f30c-df2c-4ce4-95cb-1f4087df6697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-calendar/span/input</value>
      <webElementGuid>28fbc487-8f07-4ab5-8c0f-3246b2eca31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calendar']</value>
      <webElementGuid>94b437e5-9f19-4225-a97d-a6f7b21cd372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
