<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sa_p-ripple p-element ng-tns-c66-31 ng_d4338e</name>
   <tag></tag>
   <elementGuidId>dd080dd8-bbfb-4184-a4e6-db8cb1917729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l-main']/div[4]/app-my-info-builder/div/div[4]/div/span/p-calendar/span/div/div/div/div[2]/table/tbody/tr[5]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;29&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>468a7e79-1a95-409e-b56a-7ca0f3b78439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2bcaafb1-c187-4b40-9df4-1db032361234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element ng-tns-c66-31 ng-star-inserted</value>
      <webElementGuid>dbb6ab6b-a7d2-4c30-b83f-70d9bdf2fa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>881adb4d-6b5e-4c6f-8ecb-d12ac5da529e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-main&quot;)/div[@class=&quot;main-panel&quot;]/app-my-info-builder[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;flex flex-row mb-8&quot;]/div[@class=&quot;p-fluid w-full&quot;]/span[@class=&quot;p-float-label&quot;]/p-calendar[@class=&quot;p-element p-inputwrapper ng-tns-c66-31 ng-untouched ng-pristine ng-valid ng-star-inserted p-inputwrapper-filled p-inputwrapper-focus&quot;]/span[@class=&quot;ng-tns-c66-31 p-calendar p-focus&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c66-31 p-datepicker p-component ng-star-inserted ng-animating&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c66-31 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c66-31 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c66-31 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c66-31&quot;]/tbody[@class=&quot;ng-tns-c66-31&quot;]/tr[@class=&quot;ng-tns-c66-31 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c66-31 ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c66-31 ng-star-inserted&quot;]</value>
      <webElementGuid>51e4907c-2741-4edd-8cc1-be11f8e59017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l-main']/div[4]/app-my-info-builder/div/div[4]/div/span/p-calendar/span/div/div/div/div[2]/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>517bc44b-4ada-45ed-9c46-6054c8ee7498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[30]</value>
      <webElementGuid>1028f7e0-d156-4224-91fd-af62daa64a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[31]</value>
      <webElementGuid>95e4a984-240f-476b-8424-246a609c8171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth day'])[1]/preceding::span[6]</value>
      <webElementGuid>d9cb45c9-886c-4753-8b5b-71f7f15e4a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/preceding::span[6]</value>
      <webElementGuid>14d1574c-0845-4191-b64c-33c8d9692b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='29']/parent::*</value>
      <webElementGuid>fc047ce8-9da1-4fc1-87fc-4907ab565077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span</value>
      <webElementGuid>7fd6460c-3506-40d9-bfc9-a42c2f107503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '29' or . = '29')]</value>
      <webElementGuid>ac691946-99f9-4910-8015-55627434f246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
