<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//h2[text()='Login']</description>
   <name>titleLogin</name>
   <tag></tag>
   <elementGuidId>f6e96a1a-a035-4559-97c7-556d20dab230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[normalize-space()='Login']
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
