<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nhóm chức năng Role Vỉewer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b9e9697-f96e-466f-b7cd-8af9b6ebd923</testSuiteGuid>
   <testCaseLink>
      <guid>2ed26580-0035-478c-9292-ecf8b97fa822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhom chuc nang theo Role/Viewer/Xem Profile/TCs Tổng hợp chức năng theo rẽ nhánh/TCRN01 - Xem MH Education</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e0372d1-f209-4940-9c37-2f8ac9a76e8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5893328-29de-4793-bf65-438f9c1e25be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c566273d-99cf-4345-881b-216795962f20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f18b7072-e091-46a0-8979-439bbf5e221d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54e8b4d4-74e1-44c6-8ea2-6db4b755b6ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhom chuc nang theo Role/Viewer/Xem Profile/TCs Tổng hợp chức năng theo rẽ nhánh/TCRN01 - Xem MH Profile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ef12f140-9e2a-4da0-9bb1-e8164f1250f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhom chuc nang theo Role/Viewer/Xem Profile/TCs Tổng hợp chức năng theo rẽ nhánh/TCRN01 - Xem MH Skill</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
